config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'login', to: 'sessions#login'
  get 'signup', to: 'sessions#signup'
  post 'create-user', to: 'sessions#create'

  resources :visits

  root to: 'visits#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :visits_categories
  has_many :visits, through: :visits_categories

  validates_presence_of :name
end

app/models/category_rating.rb
class CategoryRating < ApplicationRecord
  belongs_to :rating
  belongs_to :category
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :visit

  validates_presence_of :text
end

app/models/rating.rb
class Rating < ApplicationRecord
  has_many :category_ratings
  has_many :categories, through: :category_ratings

  validates_presence_of :value
end

app/models/user.rb
class User < ApplicationRecord
  has_many :visits

  validates_presence_of :first_name, :last_name, :email
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :user
  has_many :visits_categories, dependent: :destroy
  has_many :categories, through: :visits_categories, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many_attached :images, dependent: :purge_later

  validates_presence_of :address
  validates :name, presence: true, uniqueness: { scope: :user_id, message: "You already have a visit with that name" }

  before_validation :update_coordinates, if: :address_changed?

  accepts_nested_attributes_for :comments, reject_if: proc { |att| att['text'].blank? }

  private

  def update_coordinates
    geo = Geocoder.search(address).first
    return self.errors.add(:base, "Address does not exist") unless geo.present?

    self.latitude = geo.data['lat']
    self.longitude = geo.data['lon']
  end
end

app/models/visits_categories_rating.rb
class VisitsCategoriesRating < ApplicationRecord
  belongs_to :visits_category
  belongs_to :rating

  delegate :category, to: :visits_category, prefix: false
  delegate :name, to: :category, prefix: true
end

app/models/visits_category.rb
class VisitsCategory < ApplicationRecord
  belongs_to :visit
  belongs_to :category

  has_many :visits_categories_ratings, dependent: :destroy
  has_many :ratings, through: :visits_categories_ratings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordInvalid, with: :record_invalid

  private

  def record_invalid(error)
    redirect_to visits_path, alert: error.message
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login; end

  def signup
  end

  def create
    if params[:commit] == 'Login'
      if params[:email] == 'user' && params[:password] == 'password'
        flash[:success] = 'Login successful!'
        redirect_to root_path
      else
        flash[:error] = 'Invalid username or password'
        render :new
      end
    elsif params[:commit] == 'Signup'
      User.create!(user_params)
      flash[:success] = 'Signup successful!'
      redirect_to root_path
    end
  end

  private

  def user_params
    params.permit(:first_name, :last_name, :email)
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: %i[show edit update destroy]

  def index
    @visits = Visit.all
  end

  def new
    @visit = Visit.new
  end

  def edit; end

  def show
    @visits_categories_ratings = VisitsCategoriesRating.includes(:rating, visits_category: [:category])
                                                       .where(visits_category_id: @visit.visits_categories.pluck(:id))
  end

  def create
    visit = Visit.new(visit_params.except(:category_ids))
    if visit.save!
      visit.images.attach(params[:images]) if params[:images]

      category_ids = params[:visit][:category_ids]
      category_ids.each_with_index do |category_id, index|
        category = Category.find(category_id)
        visits_category = VisitsCategory.create!(visit: visit, category: category)

        value = params[:visit][:category][:ratings][index][:value]
        next unless value.present?

        visits_category.ratings.create!(value: value)
      end

      redirect_to visits_path, notice: 'Visit was successfully created.'
    end
  end

  def update
    @visit.assign_attributes(visit_params.except(:category_ids))
    @visit.images.attach(params[:images]) if params[:images]
    @visit.save!

    redirect_to visits_path, notice: 'Visit was successfully updated.'
  end

  def destroy
    @visit.destroy!
    redirect_to visits_path, notice: 'Visit was successfully destroyed.'
  end

  private

  def set_visit
    @visit = Visit.find(params[:id])
  end

  def visit_params
    params.require(:visit).permit(:name, :address, :user_id, images: [], comments_attributes: %i[id text],
                                  category_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ComeAcross</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if flash[:notice] %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if flash[:alert] %>
    <p class="alert"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/visits/_form.html.erb
<%= form_with model: visit, local: true do |form| %>
  <div class="form-group mb-3">
    <%= form.label :name, {:class => "form-label"} %>
    <%= form.text_field :name, {:class => "form-control"} %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :address, {:class => "form-label"} %>
    <%= form.text_field :address, {:class => "form-control"} %>
  </div>

  <% if visit.new_record? %>
    <div class="form-group mb-3">
      <%= form.label :category_ids, 'Categories', {:class => "form-label"} %>
      <% Category.all.each do |category| %>
        <div class="category d-flex justify-content-between mt-2">
          <div class="category-checkbox d-flex">
            <%= form.check_box :category_ids, { multiple: true }, category.id, nil %>
            <div class="category-name" style="margin-left: 15px;"><%= category.name %></div>
          </div>
          <div class="rating-checkbox">
            <%= form.fields_for 'category[ratings][]', Rating.new do |rating_fields| %>
              <%= rating_fields.label :value, 'Rating (0-10)' %>
              <%= rating_fields.number_field :value, in: 0..10, step: 1 %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: User.first.id %>

  <div class="form-group mb-3">
    <%= form.fields_for :comments, comments,  class:'form' do |comment_field| %>
      <div class="">
        <p>Comment:</p>
        <%= comment_field.text_field :text, class:"form-control" %>
      </div>
    <% end %>
  </div>


  <div class="form-group mb-3">
    <%= form.label :images, {:class => "form-label"} %>
    <%= form.file_field :images, {:class => "form-control", multiple: true} %>
  </div>

  <div>
    <%= form.submit 'Save Place', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/visits/_header.html.erb
<header header id="header" class="u-header bg-across-brand-navy">
  <div id="logoAndNav" class="container">
    <nav class="navbar">
      <%= link_to 'COME ACROSS', root_path, class:'brand-name' %>
    </nav>
  </div>
</header>

app/views/visits/edit.html.erb
<%= render 'header' %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1 class="text-center">Edit Visit</h1>
      <%= render 'form', visit: @visit, comments: @visit.comments %>
    </div>
  </div>
</div>

app/views/visits/index.html.erb
<%= render 'header' %>

<div class="container">
  <h1 class="text-center">Visits</h1>

  <div class="row">
    <div class="col-12">
      <%= link_to 'Add New Visit +', new_visit_path, class:'btn btn-primary mb-5' %>
    </div>
  </div>

  <div class="row flex-wrap">
    <% @visits.each do |visit| %>
      <div class="card" style="width: 18rem; margin-right: 15px; margin-bottom: 15px;">
        <div class="card-body">
          <h5 class="card-title"><%= visit.name %></h5>
          <p class="card-text"><%= visit.address %></p>
          <%= link_to 'View Visit', visit_path(visit), class:'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/visits/new.html.erb
<h1>New Visit</h1>

<%= form_with model: @visit, url: visits_path, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :category_ids, 'Categories' %><br>
    <% Category.all.each do |category| %>
      <%= form.check_box :category_ids, { multiple: true }, category.id, nil %>
      <%= category.name %><br>
      <%= form.fields_for 'category[ratings][]', category.ratings.build do |rating_fields| %>
        <%= rating_fields.label :value, 'Rating (0-10)' %>
        <%= rating_fields.number_field :value, in: 0..10, step: 1 %>
      <% end %>
    <% end %>
  </div>

  <%= form.hidden_field :user_id, value: User.first.id %>

  <%= form.fields_for :comment, class:'form' do |comment_field| %>
    <div class="form-group">
      <p>Comment:</p>
      <%= comment_field.text_field :text, class:"form-control" %>
    </div>
  <% end %>

  <div>
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div>
    <%= form.submit 'Create Place' %>
  </div>
<% end %>

<%= link_to 'Back', root_path %>

app/views/visits/show.html.erb
<%= render 'header' %>

<% visit = @visit %>

<div id="map" style="height: 500px;"></div>

<div class="container">
  <div class="mt-3">
    <div class="d-flex justify-content-between">
      <h3><%= visit.name %></h3>
      <div class="d-flex">
        <%= link_to 'Edit Visit', edit_visit_path(visit), class:'edit-visit', style: 'margin-right: 10px;' %>
        <%= link_to 'Delete Visit', visit_path(visit), class:'edit-visit', method: :delete, data: { confirm: 'Are you sure?' }  %>
      </div>

    </div>

    <p><%= visit.address %></p>
    <div class="d-flex">
      <p style="margin-right: 10px;">Latitude: <%= visit.latitude %></p>
      <p>Longitude: <%= visit.longitude %></p>
    </div>
  </div>

  <div class="mt-3">
    <h5>Ratings</h5>
    <% @visits_categories_ratings.each do |visits_categories_rating| %>
      <div class="d-flex">
        <div style="margin-right: 5px;"><%= visits_categories_rating.category_name %>:</div>
        <div><%= visits_categories_rating.rating.value %>/10</div>
      </div>
    <% end %>
  </div>

  <div class="mt-3">
    <h5>Images</h5>
    <% visit.images.each do |image| %>
      <%= image_tag image, style: 'height: 300px;width:300px;object-fit:cover;' %>
    <% end %>
  </div>

  <div class="mt-3">
    <h5>Comments</h5>
    <% visit.comments.each do |comment| %>
      <p><%= comment.text %></p>
    <% end %>
  </div>
</div>

<script>
    function initMap() {
        var visit = { lat: <%= @visit.latitude %>, lng: <%= @visit.longitude %> };
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 12,
            center: visit
        });
        new google.maps.Marker({
            position: visit,
            map: map,
            title: '<%= @visit.name %>'
        });
    }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_KEY'] %>&callback=initMap" async defer></script>

<%= link_to 'Back', root_path %>